/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * File transfer handle exposed to JavaScript.
 *
 * Obtained via `NapiNode.fileTransfer()`. Holds an `Arc<Node>` to create
 * fresh `FileTransfer` handles on each method call (the Rust `FileTransfer`
 * borrows `&Node`, so we can't store it across JS boundaries).
 */
export declare class NapiFileTransfer {
  /**
   * Send a file to a peer.
   *
   * `peer_id` is the recipient's stable `device_id` (RFC 017). The
   * underlying `resolve_peer_id` also accepts device names, prefixes,
   * and legacy Tailscale IDs. Resolves with transfer result on success.
   */
  sendFile(peerId: string, localPath: string, remotePath: string): Promise<NapiTransferResult>
  /**
   * Pull (download) a file from a remote peer.
   *
   * Resolves with transfer result on success.
   */
  pullFile(peerId: string, remotePath: string, localPath: string): Promise<NapiTransferResult>
  /** Auto-accept all incoming file offers, saving files to `output_dir`. */
  autoAccept(outputDir: string): Promise<void>
  /** Auto-reject all incoming file offers. */
  autoReject(): Promise<void>
  /**
   * Subscribe to incoming file offers with a callback.
   *
   * The callback receives a `NapiFileOffer`. Use `autoAccept()` or
   * `autoReject()` for automated handling, or use `onOffer()` for
   * manual inspection of offers.
   * Subscribe to incoming file offers with a callback.
   *
   * The callback receives `(offer, responder)` — call `responder.accept(path)`
   * or `responder.reject(reason)` to handle the offer. If neither is called
   * within 60 seconds, the offer is auto-rejected.
   */
  onOffer(callback: (offer: FileOffer, responder: NapiOfferResponder) => void): void
  /**
   * Subscribe to file transfer events.
   *
   * The callback receives `NapiFileTransferEvent` objects for all
   * transfer lifecycle events (hashing, progress, completed, failed, etc.).
   */
  onEvent(callback: (event: FileTransferEvent) => void): void
  /** Set the maximum allowed transfer size in bytes. */
  setMaxTransferSize(bytes: number): void
  /**
   * Register a directory whose files may be served to peers on PULL_REQUEST.
   *
   * Pull-serving is deny-by-default: only files under a registered pull root
   * are served to peers. The path is canonicalized before registration.
   */
  addPullRoot(root: string): void
  /**
   * List the currently registered pull roots.
   *
   * Pull-serving is deny-by-default: only files under a registered pull root
   * are served to peers.
   */
  pullRoots(): Array<string>
  /**
   * Clear all registered pull roots.
   *
   * Pull-serving is deny-by-default: with no roots registered, no files are
   * served to peers.
   */
  clearPullRoots(): void
}

/**
 * The main truffle node exposed to JavaScript.
 *
 * Lifecycle:
 * 1. `new NapiNode()` — creates an empty wrapper.
 * 2. `await node.start(config)` — builds and starts the underlying `Node<TailscaleProvider>`.
 * 3. Use `getPeers()`, `send()`, `onPeerChange()`, etc.
 * 4. `await node.stop()` — shuts down the node.
 */
export declare class NapiNode {
  /** Create a new (unstarted) NapiNode. */
  constructor()
  /**
   * Install a callback to receive the Tailscale auth URL.
   *
   * Must be called BEFORE `start()`. During startup the Tailscale
   * provider may require interactive authentication; if so, this
   * callback is invoked with the auth URL while `start()` is still
   * waiting. If no callback is installed, `start()` uses the plain
   * build path and may reject with "timed out waiting for
   * authentication" after 5 minutes.
   */
  onAuthRequired(callback: (url: string) => void): void
  /**
   * Start the node with the given configuration.
   *
   * Resolves when the Tailscale sidecar is connected and the node is ready.
   *
   * # Safety
   * This takes `&mut self` in an async context. The caller must ensure that
   * no other calls are made on this NapiNode while `start()` is in progress.
   */
  start(config: NapiNodeConfig): Promise<void>
  /**
   * Stop the node and release all resources.
   *
   * # Safety
   * This takes `&mut self` in an async context. The caller must ensure that
   * no other calls are made on this NapiNode while `stop()` is in progress.
   */
  stop(): Promise<void>
  /** Get the local node's identity. */
  getLocalInfo(): NapiNodeIdentity
  /**
   * Get all known peers.
   *
   * Each peer's `deviceId` is the remote ULID only once that peer's hello
   * has been received over the envelope-bus WebSocket (`wsConnected == true`);
   * before then it falls back to the peer's Tailscale stable id (equal to
   * `tailscaleId`) and flips to the ULID when the session connects.
   * Raw-transport-only callers should key identity on `tailscaleId`. See
   * `NapiPeer`.
   */
  getPeers(): Promise<Array<NapiPeer>>
  /** Resolve a peer identifier (name or ID) to the canonical node ID. */
  resolvePeerId(peerId: string): Promise<string>
  /** Ping a peer and return latency info. */
  ping(peerId: string): Promise<NapiPingResult>
  /** Get health information from the network layer. */
  health(): Promise<NapiHealthInfo>
  /** Send a namespaced message to a specific peer. */
  send(peerId: string, namespace: string, data: Buffer): Promise<void>
  /** Broadcast a namespaced message to all connected peers. */
  broadcast(namespace: string, data: Buffer): Promise<void>
  /**
   * Open a raw TCP connection to a peer on the given port (RFC 021).
   *
   * `host` accepts a device id (or a unique ≥4-char prefix), device
   * name, Tailscale hostname, or Tailscale IP. The returned socket is
   * pull-model — see `NapiTcpSocket`; the `@vibecook/truffle` package
   * wraps it in a `stream.Duplex`.
   */
  openTcp(host: string, port: number): Promise<NapiTcpSocket>
  /**
   * Listen for raw TCP connections on a port (RFC 021).
   *
   * Port 0 binds an ephemeral port — read the resolved port from the
   * returned listener. Ports 443 and 9417 are reserved.
   */
  listenTcp(port: number): Promise<NapiTcpListener>
  /**
   * Bind a UDP datagram socket on a port (RFC 021).
   *
   * Datagram boundaries are preserved; keep payloads ≤ ~1,200 bytes
   * (tailnet MTU). Port 0 binds an ephemeral relay port — suitable for
   * client-style sockets that send first.
   */
  bindUdp(port: number): Promise<NapiUdpSocket>
  /**
   * Open a raw QUIC connection to a peer on the given port (RFC 021).
   *
   * The connection carries multiple concurrent bidirectional byte
   * streams with no head-of-line blocking. Only same-app peers can
   * complete the handshake (ALPN scoping). `host` accepts the same
   * identifier forms as `openTcp`.
   */
  connectQuic(host: string, port: number): Promise<NapiQuicConnection>
  /**
   * Listen for raw QUIC connections on a port (RFC 021).
   *
   * Ports 443 and 9417 are reserved; port 0 is not supported over the
   * tsnet relay — choose an explicit port.
   */
  listenQuic(port: number): Promise<NapiQuicListener>
  /**
   * Subscribe to peer change events.
   *
   * The callback receives `NapiPeerEvent` objects whenever peers
   * join, leave, connect, disconnect, or update.
   */
  onPeerChange(callback: (event: PeerEvent) => void): void
  /**
   * Subscribe to messages on a specific namespace.
   *
   * The callback receives `NapiNamespacedMessage` objects.
   */
  onMessage(namespace: string, callback: (msg: NamespacedMessage) => void): void
  /** Get a `NapiFileTransfer` handle for file transfer operations. */
  fileTransfer(): NapiFileTransfer
  /** Get a `NapiProxy` handle for reverse proxy operations. */
  proxy(): NapiProxy
  /**
   * Get a `NapiSyncedStore` handle for synchronized state operations.
   *
   * Each call creates a new store instance with the given `store_id`.
   * Multiple stores can coexist with different IDs.
   */
  syncedStore(storeId: string): NapiSyncedStore
}

/**
 * Responder for accepting or rejecting a file offer from JS.
 *
 * The responder is consumed on the first call to `accept()` or `reject()`.
 * If neither is called, the offer times out after 60 seconds.
 */
export declare class NapiOfferResponder {
  /** Accept the file offer, saving to the specified path. */
  accept(savePath: string): Promise<void>
  /** Reject the file offer with a reason. */
  reject(reason: string): Promise<void>
}

/**
 * Reverse proxy handle exposed to JavaScript.
 *
 * Obtained via `NapiNode.proxy()`. Holds an `Arc<Node>` to create
 * fresh `Proxy` handles on each method call (the Rust `Proxy` borrows
 * `&Node`, so we can't store it across JS boundaries).
 */
export declare class NapiProxy {
  /**
   * Add a reverse proxy that forwards traffic from a TLS port on the mesh
   * to a local target.
   */
  add(config: NapiProxyConfig): Promise<NapiProxyInfo>
  /** Remove a reverse proxy by ID. */
  remove(id: string): Promise<void>
  /** List all active proxies on this node. */
  list(): Promise<Array<NapiProxyInfo>>
  /**
   * Subscribe to proxy lifecycle events.
   *
   * The callback receives `NapiProxyEvent` objects whenever a proxy
   * starts, stops, or encounters an error.
   */
  onEvent(callback: (event: NapiProxyEvent) => void): void
}

/**
 * A raw QUIC connection to a peer over the mesh.
 *
 * Open streams with `openStream()`; accept peer-opened streams with
 * `acceptStream()` (resolves `null` once the connection closes). Streams
 * are lazy — the peer's accept does not fire until the opener writes.
 */
export declare class NapiQuicConnection {
  /** Open a new bidirectional byte stream on this connection. */
  openStream(): Promise<NapiQuicStream>
  /**
   * Accept the next stream the peer opens.
   *
   * Resolves `null` once the connection has closed (either side).
   */
  acceptStream(): Promise<NapiQuicStream | null>
  /** The peer's tailnet address (`100.x.x.x:port` over the relay). */
  remoteAddress(): string
  /**
   * The peer's stable device id when known. `null` means "anonymous but
   * tailnet-authenticated".
   */
  remotePeerId(): string | null
  /** Close the connection and all its streams. Idempotent. */
  close(): void
}

/** A listener for raw QUIC connections on a mesh port. */
export declare class NapiQuicListener {
  /**
   * Accept the next incoming connection.
   *
   * Resolves `null` once the listener has been closed. Cross-app
   * connection attempts fail the TLS handshake (ALPN scoping) and are
   * skipped, never surfaced.
   */
  accept(): Promise<NapiQuicConnection | null>
  /** The port this listener is bound to. */
  port(): number
  /**
   * Close the listener and connections accepted from it. Pending
   * `accept()` calls resolve with `null`. Idempotent.
   */
  close(): void
}

/**
 * A bidirectional byte stream on a QUIC connection.
 *
 * Behaves like an independent TCP connection (ordered, reliable,
 * flow-controlled) without head-of-line blocking against sibling streams.
 * Pull-model reads, like `NapiTcpSocket`.
 */
export declare class NapiQuicStream {
  /**
   * Read up to `maxBytes` (default 64 KiB) from the stream.
   *
   * Resolves with the next chunk, or `null` on clean EOF (the peer
   * finished the stream) and after `close()`.
   */
  read(maxBytes?: number | undefined | null): Promise<Buffer | null>
  /** Write all of `data` to the stream (respects QUIC flow control). */
  write(data: Buffer): Promise<void>
  /**
   * Half-close: finish the write side, signalling clean EOF to the
   * peer. Reading remains possible. Idempotent.
   */
  finish(): Promise<void>
  /**
   * Fully close the stream (finish writes, stop reads). Unblocks any
   * pending `read()` (it resolves `null`). Idempotent.
   */
  close(): Promise<void>
}

/**
 * Synchronized store handle exposed to JavaScript.
 *
 * Obtained via `NapiNode.syncedStore(storeId)`. Each store instance manages
 * device-owned slices of JSON data that are automatically synchronized
 * across the mesh.
 */
export declare class NapiSyncedStore {
  /** Update this device's data in the store. */
  set(data: any): Promise<void>
  /** Get this device's current data, or `null` if `set()` hasn't been called. */
  local(): Promise<any | null>
  /** Get a specific peer's slice by device ID. */
  get(deviceId: string): Promise<NapiSlice | null>
  /** Get all slices (local + remote) as an array. */
  all(): Promise<Array<NapiSlice>>
  /** Get all device IDs that have data in this store. */
  deviceIds(): Promise<Array<string>>
  /** The store identifier. */
  storeId(): string
  /** Current local version number. */
  version(): number
  /**
   * Subscribe to store change events.
   *
   * The callback receives `NapiStoreEvent` objects whenever local data
   * changes, a peer's data is updated, or a peer is removed.
   */
  onChange(callback: (event: StoreEvent) => void): void
  /**
   * Stop the store and cancel all event-forwarding tasks.
   *
   * # Safety
   * This takes `&mut self` in an async context. The caller must ensure that
   * no other calls are made on this NapiSyncedStore while `stop()` is in progress.
   */
  stop(): Promise<void>
}

/** A listener for raw TCP connections on a mesh port. */
export declare class NapiTcpListener {
  /**
   * Accept the next incoming connection.
   *
   * Resolves with `null` once the listener has been closed.
   */
  accept(): Promise<NapiTcpSocket | null>
  /** The port this listener is bound to (resolved when 0 was requested). */
  port(): number
  /**
   * Close the listener and release the tsnet port in the sidecar.
   * Pending `accept()` calls resolve with `null`. Idempotent.
   */
  close(): Promise<void>
}

/**
 * A raw TCP connection to a peer over the mesh.
 *
 * Reads are pull-model: `read()` resolves with the next chunk, `null` on
 * clean EOF. Writes resolve once the bytes are handed to the transport
 * (respecting backpressure). `end()` half-closes the write side (FIN);
 * `close()` tears down both directions. Dropping the JS object without
 * closing also closes the socket (no background tasks are held).
 */
export declare class NapiTcpSocket {
  /**
   * Read up to `maxBytes` (default 64 KiB) from the socket.
   *
   * Resolves with the next chunk of data, or `null` on clean EOF (the
   * peer finished writing) and after `close()`.
   */
  read(maxBytes?: number | undefined | null): Promise<Buffer | null>
  /** Write all of `data` to the socket. */
  write(data: Buffer): Promise<void>
  /**
   * Half-close the write side (send FIN), like `socket.end()`.
   *
   * Reading remains possible until the peer closes its side. Idempotent.
   */
  end(): Promise<void>
  /**
   * Fully close the socket (both directions). Unblocks any pending
   * `read()` (it resolves `null`). Idempotent.
   */
  close(): Promise<void>
  /**
   * The logical remote address (`host:port` for outbound connections,
   * the peer's tailnet address for inbound ones).
   */
  remoteAddress(): string
  /**
   * The peer's stable id when known — the resolved device id for
   * outbound connections, the WhoIs node id for inbound ones. `null`
   * means "anonymous but tailnet-authenticated" (never gate on it).
   */
  remotePeerId(): string | null
  /** Human-readable peer name from the WhoIs identity (inbound only). */
  remotePeerName(): string | null
}

/**
 * A UDP socket on the mesh.
 *
 * Datagram boundaries are preserved end-to-end. Keep payloads ≤ ~1,200
 * bytes to stay under the tailnet MTU (larger datagrams fragment in the
 * userspace netstack and become loss-prone). IPv4 (`100.x`) peers only.
 */
export declare class NapiUdpSocket {
  /**
   * Send a datagram to `host:port`.
   *
   * `host` accepts a peer's device id (or unique ≥4-char prefix),
   * device name, Tailscale hostname, or Tailscale IP. Resolves with
   * the number of payload bytes sent.
   */
  send(data: Buffer, host: string, port: number): Promise<number>
  /**
   * Receive the next datagram.
   *
   * Resolves `null` once the socket has been closed. Note UDP is
   * unreliable: datagrams may be dropped or reordered.
   */
  recv(): Promise<NapiDatagram | null>
  /**
   * The mesh port this socket is bound to (the tsnet port over the
   * relay; 0 for ephemeral client-style sockets whose tsnet port is
   * unknown — see RFC 021).
   */
  port(): number
  /**
   * Close the socket. Any in-flight `recv()` resolves with `null`.
   * Idempotent.
   */
  close(): void
}

/** A datagram received from the mesh. */
export interface NapiDatagram {
  data: Buffer
  /** Sender's tailnet IP (`100.x.x.x`) — WireGuard-authenticated. */
  address: string
  /** Sender's source port. */
  port: number
}

/** An incoming file offer from a remote peer. */
export interface NapiFileOffer {
  /** Sender's stable `device_id` (ULID) from the RFC 017 hello envelope. */
  fromPeer: string
  /** Human-readable device name of the sending peer. */
  fromName: string
  /** File name being offered. */
  fileName: string
  /** File size in bytes. */
  size: number
  /** Expected SHA-256 hash (hex). */
  sha256: string
  /** Suggested save path from the sender. */
  suggestedPath: string
  /** Unique token for this transfer. */
  token: string
}

/** Events emitted by the file transfer subsystem. */
export interface NapiFileTransferEvent {
  /**
   * Event type: "offer_received", "hashing", "waiting_for_accept",
   * "progress", "completed", "rejected", "failed".
   */
  eventType: string
  /** Transfer token (if applicable). */
  token?: string
  /** File name (if applicable). */
  fileName?: string
  /** Direction: "send" or "receive" (if applicable). */
  direction?: string
  /** Progress info (present for "progress" events). */
  progress?: NapiTransferProgress
  /** Offer info (present for "offer_received" events). */
  offer?: NapiFileOffer
  /** Bytes transferred (present for "completed" events). */
  bytesTransferred?: number
  /** SHA-256 hash (present for "completed" events). */
  sha256?: string
  /** Elapsed seconds (present for "completed" events). */
  elapsedSecs?: number
  /** Reason for rejection or failure. */
  reason?: string
  /** Bytes hashed so far (present for "hashing" events). */
  bytesHashed?: number
  /** Total bytes to hash (present for "hashing" events). */
  totalBytes?: number
}

/** Health information from the network layer. */
export interface NapiHealthInfo {
  /** Current backend state (e.g., "Running", "NeedsLogin"). */
  state: string
  /** Key expiry timestamp (RFC 3339), if applicable. */
  keyExpiry?: string
  /** Active health warnings. */
  warnings: Array<string>
  /** Whether the network is fully operational. */
  healthy: boolean
}

/** A message received on a specific namespace. */
export interface NapiNamespacedMessage {
  /** Sender's stable `device_id` (ULID) from the RFC 017 hello envelope. */
  from: string
  /** Namespace the message was sent on. */
  namespace: string
  /** Application-defined message type. */
  msgType: string
  /** Opaque JSON payload (as a JS value via serde). */
  payload: any
  /** Millisecond Unix timestamp from the sender, if set. */
  timestamp?: number
}

/** Configuration for starting a Node (RFC 017 §7 shape). */
export interface NapiNodeConfig {
  /**
   * Application namespace identifier. Required. Must match
   * `^[a-z][a-z0-9-]{1,31}$`; validated on the Rust side.
   */
  appId: string
  /**
   * Optional human-readable device name. Defaults to the OS hostname.
   * May contain any Unicode characters; the Tailscale hostname is
   * derived automatically.
   */
  deviceName?: string
  /**
   * Optional stable ULID override. Auto-generated (and persisted) when
   * omitted.
   */
  deviceId?: string
  /**
   * Tailscale state directory. Defaults to
   * `{userDataDir}/truffle/{app_id}/{slug(device_name)}`.
   */
  stateDir?: string
  /** Path to the Go sidecar binary. */
  sidecarPath: string
  /** Tailscale auth key for headless authentication. */
  authKey?: string
  /** Whether the node is ephemeral (auto-removed from tailnet on shutdown). */
  ephemeral?: boolean
  /** WebSocket listen port. Defaults to 9417. */
  wsPort?: number
}

/** Identity of the local node (RFC 017 §7.2). */
export interface NapiNodeIdentity {
  /** Application namespace identifier. */
  appId: string
  /**
   * This node's own stable ULID (RFC 017 §5.4). Primary key for device
   * identity. Always the real ULID — unlike a *peer's* `deviceId` (see
   * `NapiPeer`), which falls back to a Tailscale id until that peer's
   * hello is seen. Persists across restarts, including with
   * `ephemeral: true`.
   */
  deviceId: string
  /** Original (unsanitised) device name, as passed by the application. */
  deviceName: string
  /** The Tailscale hostname (`truffle-{appId}-{slug}`). Debug use only. */
  tailscaleHostname: string
  /**
   * This node's Tailscale stable node ID. Escape hatch for diagnostics;
   * with `ephemeral: true` it rotates on each restart while `deviceId`
   * persists.
   */
  tailscaleId: string
  /** DNS name on the tailnet, if available. */
  dnsName?: string
  /** Tailscale IP address as a string, if available. */
  ip?: string
}

/** A peer as seen by application code (RFC 017 §7.3). */
export interface NapiPeer {
  /**
   * Remote device identity. Equals the remote node's stable **ULID** only
   * once its identity has been learned over the envelope-bus WebSocket hello
   * (RFC 017 §8) — i.e. once `wsConnected` is `true`. Until then, and
   * permanently for raw-transport-only apps that never open the bus, it
   * falls back to the peer's **Tailscale stable node id** (the same value as
   * `tailscaleId`). It therefore CHANGES from the Tailscale id to the ULID
   * the moment the WS session connects (verified by probe: the flip is
   * simultaneous with `wsConnected` going true, and does not regress) — do
   * NOT treat it as stable within a session. Code that keys peers by
   * identity while using only the raw transports (QUIC/TCP/UDP) should key
   * on `tailscaleId` instead.
   */
  deviceId: string
  /**
   * Human-readable device name from the remote node's hello. Falls back to
   * the Tailscale hostname (slug) until `wsConnected` is `true`, on the
   * same rule as `deviceId`.
   */
  deviceName: string
  /** Network IP address as a string. */
  ip: string
  /** Whether the peer is online (from Layer 3). */
  online: boolean
  /**
   * Whether an envelope-bus WebSocket session is currently open to this
   * peer. Also gates `deviceId` / `deviceName`: while `false` they are the
   * Tailscale-stable-id / hostname fallback; the first time it becomes
   * `true` the RFC 017 hello lands and both flip to the remote ULID / real
   * name. Raw-transport-only apps (that never call `send`/`broadcast`/
   * `onMessage`) keep this `false` and so never see the ULID here.
   */
  wsConnected: boolean
  /** Connection type description (e.g., "direct" or "relay:ord"). */
  connectionType: string
  /** Operating system, if known. */
  os?: string
  /** Last time the peer was seen online (RFC 3339 string). */
  lastSeen?: string
  /**
   * Tailscale stable node id — the peer's transport routing key and the ONLY
   * identity here that is stable for the whole session. Prefer this as the
   * map key for raw-transport-only apps, where `deviceId` never becomes the
   * ULID (no WS hello is exchanged) and would otherwise change under you. For
   * apps on the envelope bus, `deviceId` (the ULID, once `wsConnected`) is
   * the portable cross-restart identity.
   */
  tailscaleId: string
}

/** A peer change event delivered to JS. */
export interface NapiPeerEvent {
  /** Event type: "joined", "left", "updated", "ws_connected", "ws_disconnected", "auth_required". */
  eventType: string
  /**
   * `device_id` of the affected peer — the ULID once the peer's hello has
   * been seen, otherwise the Tailscale stable id fallback (same rule as
   * `NapiPeer.deviceId`). `left` / `ws_disconnected` events in
   * particular often carry the Tailscale id because the hello may already be
   * gone. Empty string for `auth_required` events (no associated peer).
   */
  peerId: string
  /** Full peer info (present for joined/updated events). */
  peer?: NapiPeer
  /** Auth URL (present only for auth_required events). */
  authUrl?: string
}

/** Result of a network-level ping. */
export interface NapiPingResult {
  /** Round-trip latency in milliseconds. */
  latencyMs: number
  /** Connection type description (e.g., "direct" or "relay:sfo"). */
  connection: string
  /** Direct peer endpoint address, if available. */
  peerAddr?: string
}

/** Configuration for adding a reverse proxy, received from JavaScript. */
export interface NapiProxyConfig {
  /** Unique identifier (user-chosen or auto-generated). */
  id: string
  /** Human-readable name for the proxy. */
  name: string
  /** Port on which the proxy listens on the tailnet (NAPI uses i32). */
  listenPort: number
  /** Target host (default: "localhost"). */
  targetHost?: string
  /** Target port (the local service port). */
  targetPort: number
  /** Target scheme: "http" or "https" (default: "http"). */
  targetScheme?: string
  /** Whether to announce this proxy on the mesh for discovery (default: true). */
  announce?: boolean
}

/** A proxy lifecycle event delivered to JavaScript. */
export interface NapiProxyEvent {
  /** Event type: "started", "stopped", "error". */
  eventType: string
  /** Proxy ID. */
  id: string
  /** Fully qualified URL (present for "started" events). */
  url?: string
  /** Listen port (present for "started" events). */
  listenPort?: number
  /** Error code (present for "error" events). */
  code?: string
  /** Error message (present for "error" events). */
  message?: string
}

/** Information about a running or configured proxy, returned to JavaScript. */
export interface NapiProxyInfo {
  id: string
  name: string
  listenPort: number
  targetHost: string
  targetPort: number
  targetScheme: string
  url: string
  /** Status: "starting", "running", "stopped", or "error: <message>". */
  status: string
}

/** A versioned slice of data owned by a single device. */
export interface NapiSlice {
  /**
   * Owning device's stable `device_id` (ULID) from the RFC 017 hello
   * envelope.
   */
  deviceId: string
  /** The data (JSON value). */
  data: any
  /** Monotonically increasing version (per-device). */
  version: number
  /** When this version was created (Unix milliseconds). */
  updatedAt: number
}

/** A store change event delivered to JS. */
export interface NapiStoreEvent {
  /** Event type: "local_changed", "peer_updated", "peer_removed". */
  eventType: string
  /**
   * Stable `device_id` (ULID) of the affected device (present for
   * peer_updated / peer_removed events).
   */
  deviceId?: string
  /** Data payload (present for local_changed/peer_updated events). */
  data?: any
  /** Version number (present for peer_updated events). */
  version?: number
}

/** Progress update for an in-flight file transfer. */
export interface NapiTransferProgress {
  /** Unique token for this transfer. */
  token: string
  /** Direction: "send" or "receive". */
  direction: string
  /** File name being transferred. */
  fileName: string
  /** Bytes transferred so far. */
  bytesTransferred: number
  /** Total file size in bytes. */
  totalBytes: number
  /** Current transfer speed in bytes per second. */
  speedBps: number
}

/** Result of a completed file transfer. */
export interface NapiTransferResult {
  /** Number of bytes transferred. */
  bytesTransferred: number
  /** SHA-256 hash of the transferred file. */
  sha256: string
  /** Elapsed time in seconds. */
  elapsedSecs: number
}
