/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * NapiFileTransferAdapter - Node.js wrapper for file transfer signaling.
 *
 * Handles file transfer offer/accept/reject/cancel via the mesh message bus.
 * Progress events use the broadcast channel (drops allowed for lag recovery).
 */
export declare class NapiFileTransferAdapter {
  /**
   * Create a new FileTransferAdapter.
   *
   * Sets up the underlying FileTransferManager and adapter with default TCP dial.
   */
  constructor(config: NapiFileTransferAdapterConfig)
  /**
   * Initiate sending a file to a target device.
   * Returns the transfer ID.
   */
  sendFile(targetDeviceId: string, filePath: string): Promise<string>
  /** Accept an incoming file transfer offer. */
  acceptTransfer(offer: NapiFileTransferOffer, savePath?: string | undefined | null): Promise<void>
  /** Reject an incoming file transfer offer. */
  rejectTransfer(offer: NapiFileTransferOffer, reason: string): Promise<void>
  /** Cancel an active transfer. */
  cancelTransfer(transferId: string): Promise<void>
  /** Get all tracked transfers. */
  getTransfers(): Promise<Array<NapiAdapterTransferInfo>>
  /**
   * Handle an incoming message from the mesh bus.
   * Call this when a file-transfer namespace message arrives.
   */
  handleBusMessage(msgType: string, payload: any): Promise<void>
  /**
   * Subscribe to adapter events (offers, progress, completed, failed, cancelled).
   *
   * Only one subscriber allowed. Can be called before or after `start_manager_events`.
   */
  onEvent(callback: (err: null | Error, event: NapiFileTransferEvent) => void): void
  /**
   * Subscribe to outgoing bus messages.
   *
   * The adapter generates outgoing messages (OFFER, ACCEPT, REJECT, CANCEL)
   * that must be sent via the mesh message bus. Can be called before or after
   * `start_manager_events`.
   */
  onBusMessage(callback: (err: null | Error, message: NapiBusMessage) => void): void
  /**
   * Start forwarding manager events to the adapter.
   *
   * The FileTransferManager emits events (progress, complete, error) that
   * the adapter needs to process. Call this once after construction.
   * Also spawns any pending event/bus callbacks registered before a Tokio
   * runtime was available.
   */
  startManagerEvents(): Promise<void>
}

/**
 * NapiMeshNode - Node.js wrapper for TruffleRuntime.
 *
 * Manages the full lifecycle: BridgeManager, GoShim sidecar, ConnectionManager,
 * and MeshNode via the unified TruffleRuntime. The sidecar provides Tailscale
 * connectivity; the bridge routes TCP streams; the connection manager upgrades
 * them to WebSocket; and the mesh node handles device discovery, election,
 * and messaging.
 *
 * ## RFC 009 Phase 5
 * Message events normalize namespace and message type strings to kebab-case.
 * Protocol version info is exposed via `protocolVersion()`.
 */
export declare class NapiMeshNode {
  /**
   * Create a new MeshNode.
   *
   * The `config` parameter matches the TypeScript `MeshNodeConfig` interface.
   */
  constructor(config: NapiMeshNodeConfig)
  /**
   * Start the mesh node.
   *
   * If `sidecarPath` was provided, this spawns the Go sidecar process,
   * creates a BridgeManager to route connections, and wires everything
   * together for full Tailscale mesh networking.
   */
  start(): Promise<void>
  /** Stop the mesh node and sidecar. */
  stop(): Promise<void>
  /** Check if the node is running. */
  isRunning(): Promise<boolean>
  /** Get the local device info. */
  localDevice(): Promise<NapiBaseDevice>
  /** Get the local device ID. */
  deviceId(): Promise<string>
  /** Get all known devices. */
  devices(): Promise<Array<NapiBaseDevice>>
  /** Get a device by ID. */
  deviceById(id: string): Promise<NapiBaseDevice | null>
  /** Check if this node is the primary. */
  isPrimary(): Promise<boolean>
  /** Get the current primary device ID. */
  primaryId(): Promise<string | null>
  /** Get the current role as a string ("primary" or "secondary"). */
  role(): Promise<string>
  /**
   * Send a mesh envelope to a specific device.
   * Returns true if the message was sent successfully.
   */
  sendEnvelope(deviceId: string, namespace: string, msgType: string, payload: any): Promise<boolean>
  /** Broadcast a mesh envelope to all connected devices. */
  broadcastEnvelope(namespace: string, msgType: string, payload: any): Promise<void>
  /** Get the current auth status ("unknown", "required", "authenticated"). */
  authStatus(): Promise<string>
  /** Get the current auth URL, if auth is required. */
  authUrl(): Promise<string | null>
  /**
   * Get the protocol version supported by this node.
   *
   * Returns the maximum protocol version this node speaks (currently 3,
   * the RFC 009 wire format). Use this to check compatibility with peers
   * or to display version info in a UI.
   */
  protocolVersion(): number
  /** Get the message bus for namespace-based pub/sub. */
  messageBus(): NapiMessageBus
  /** Handle tailnet peers update from the sidecar. */
  handleTailnetPeers(peers: Array<NapiTailnetPeer>): Promise<void>
  /** Set the local device as online with its Tailscale IP. */
  setLocalOnline(tailscaleIp: string, dnsName?: string | undefined | null): Promise<void>
  /**
   * Subscribe to mesh events.
   *
   * Uses ThreadsafeFunction with Blocking mode per RFC 003:
   * - Critical events (device join/leave, election, errors) are never dropped
   * - If the JS event queue is full, Rust waits rather than dropping events
   *
   * The callback receives NapiMeshEvent objects with event_type, device_id, and payload.
   *
   * Can be called multiple times to add multiple subscribers.
   * Can be called before or after `start()`. If called before `start()`, the
   * event loop is spawned when `start()` is called.
   */
  onEvent(callback: (err: null | Error, event: NapiMeshEvent) => void): void
}

/**
 * NapiMessageBus - Node.js wrapper for MeshMessageBus.
 *
 * Provides namespace-based pub/sub for application-level messages.
 */
export declare class NapiMessageBus {
  /** Get all subscribed namespaces. */
  subscribedNamespaces(): Promise<Array<string>>
  /** Dispose the message bus, clearing all handlers. */
  dispose(): Promise<void>
}

/**
 * NapiStoreSyncAdapter - Node.js wrapper for cross-device state sync.
 *
 * In the JS layer, stores are registered via the SyncableStore trait.
 * For NAPI, we expose the adapter's lifecycle and message handling.
 */
export declare class NapiStoreSyncAdapter {
  /**
   * Create a new StoreSyncAdapter.
   *
   * Note: In the NAPI layer, stores must be registered separately.
   * This constructor creates the adapter with an empty store list.
   */
  constructor(config: NapiStoreSyncConfig)
  /**
   * Start syncing.
   *
   * If `on_outgoing` was called before `start`, the outgoing loop is
   * spawned here inside the NAPI Tokio runtime context.
   */
  start(): Promise<void>
  /** Stop syncing. */
  stop(): Promise<void>
  /** Dispose the adapter. */
  dispose(): Promise<void>
  /** Handle an incoming sync message from a remote device. */
  handleSyncMessage(from: string | undefined | null, msgType: string, payload: any): Promise<void>
  /** Handle a device going offline. */
  handleDeviceOffline(deviceId: string): Promise<void>
  /** Handle a new device being discovered. */
  handleDeviceDiscovered(deviceId: string): Promise<void>
  /** Notify that a local store changed (triggers sync broadcast). */
  handleLocalChanged(storeId: string, slice: NapiDeviceSlice): Promise<void>
  /**
   * Subscribe to outgoing sync messages.
   *
   * The callback receives messages that should be broadcast to all devices
   * via the mesh message bus. Can be called before or after `start()`.
   */
  onOutgoing(callback: (err: null | Error, message: NapiOutgoingSyncMessage) => void): void
}

/** Transfer info returned to JS. */
export interface NapiAdapterTransferInfo {
  transferId: string
  direction: string
  state: string
  peerDeviceId: string
  fileName: string
  fileSize: number
  bytesTransferred: number
  percent: number
  bytesPerSecond: number
  eta: number
}

/** A device in the mesh network (JS representation). */
export interface NapiBaseDevice {
  id: string
  deviceType: string
  name: string
  tailscaleHostname: string
  tailscaleDnsName?: string
  tailscaleIp?: string
  role?: string
  status: string
  capabilities: Array<string>
  metadata?: any
  lastSeen?: number
  startedAt?: number
  os?: string
  latencyMs?: number
}

/** Outgoing bus message (sent from adapter to be relayed via mesh). */
export interface NapiBusMessage {
  targetDeviceId: string
  messageType: string
  payload: string
}

/** Device slice (JS representation). */
export interface NapiDeviceSlice {
  deviceId: string
  data: any
  updatedAt: number
  version: number
}

/** File transfer adapter configuration (JS representation). */
export interface NapiFileTransferAdapterConfig {
  /** Local device ID. */
  deviceId: string
  /** Local address for file transfers (e.g. "host.ts.net:9417"). */
  localAddr: string
  /** Default output directory for received files. */
  outputDir: string
  /** Maximum file size in bytes. */
  maxFileSize?: number
  /** Max concurrent incoming transfers. */
  maxConcurrentRecv?: number
  /** Progress event interval in milliseconds. */
  progressIntervalMs?: number
  /** Progress event byte threshold. */
  progressBytes?: number
}

/** File transfer event delivered to JS. */
export interface NapiFileTransferEvent {
  eventType: string
  transferId?: string
  payload: any
}

/** File transfer offer (JS representation, for accept/reject). */
export interface NapiFileTransferOffer {
  transferId: string
  senderDeviceId: string
  senderAddr: string
  fileName: string
  fileSize: number
  fileSha256: string
  token: string
}

/** An incoming mesh message from a peer (JS representation). */
export interface NapiIncomingMessage {
  from?: string
  connectionId: string
  namespace: string
  msgType: string
  payload: any
}

/** A mesh event delivered to JS via ThreadsafeFunction. */
export interface NapiMeshEvent {
  eventType: string
  deviceId?: string
  payload: any
}

/** Configuration for creating a MeshNode. */
export interface NapiMeshNodeConfig {
  deviceId: string
  deviceName: string
  deviceType: string
  hostnamePrefix: string
  /**
   * Path to the Go sidecar binary. Optional — use `resolveSidecarPath()`
   * from `@vibecook/truffle` for automatic platform detection.
   */
  sidecarPath?: string
  stateDir?: string
  authKey?: string
  preferPrimary?: boolean
  staticPath?: string
  capabilities?: Array<string>
  timing?: NapiMeshTimingConfig
  /** If true, the node is ephemeral (cleaned up when offline). */
  ephemeral?: boolean
  /** ACL tags to advertise (e.g. ["tag:truffle"]). */
  tags?: Array<string>
}

/** Timing configuration for the mesh. */
export interface NapiMeshTimingConfig {
  announceIntervalMs?: number
  discoveryTimeoutMs?: number
  electionTimeoutMs?: number
  primaryLossGraceMs?: number
  heartbeatPingMs?: number
  heartbeatTimeoutMs?: number
}

/** Outgoing sync message delivered to JS for broadcasting. */
export interface NapiOutgoingSyncMessage {
  msgType: string
  payload: any
}

/** Store sync configuration (JS representation). */
export interface NapiStoreSyncConfig {
  localDeviceId: string
}

/** Tailnet peer info (JS representation). */
export interface NapiTailnetPeer {
  id: string
  hostname: string
  dnsName: string
  tailscaleIps: Array<string>
  online: boolean
  os?: string
  curAddr?: string
  relay?: string
  lastSeen?: string
  keyExpiry?: string
  expired?: boolean
}
