/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A CRDT document synchronized across the mesh, exposed to JavaScript.
 *
 * Obtained via `NapiNode.crdtDoc(docId)`. Each document wraps a Loro
 * `LoroDoc` with automatic peer-to-peer sync.
 */
export declare class NapiCrdtDoc {
  /** Insert a key-value pair into a named map container. */
  mapInsert(container: string, key: string, value: any): void
  /** Delete a key from a named map container. */
  mapDelete(container: string, key: string): void
  /** Push a value to the end of a named list container. */
  listPush(container: string, value: any): void
  /** Insert a value at a specific index in a named list container. */
  listInsert(container: string, index: number, value: any): void
  /** Delete elements from a named list container. */
  listDelete(container: string, index: number, len: number): void
  /** Insert a string at a unicode position in a named text container. */
  textInsert(container: string, pos: number, text: string): void
  /** Delete text at a unicode position in a named text container. */
  textDelete(container: string, pos: number, len: number): void
  /** Increment a named counter container by the given value. */
  counterIncrement(container: string, value: number): void
  /** Get the deep JSON value of the entire document. */
  getDeepValue(): any
  /** Commit pending changes. Triggers sync to peers. */
  commit(): void
  /** The document identifier. */
  docId(): string
  /**
   * Subscribe to document change events.
   *
   * The callback receives `NapiCrdtDocEvent` objects whenever a local
   * change is applied, a remote change is received, or a peer syncs.
   */
  onChange(callback: (event: CrdtDocEvent) => void): void
  /**
   * Stop the document and cancel all event-forwarding tasks.
   *
   * # Safety
   * This takes `&mut self` in an async context. The caller must ensure that
   * no other calls are made on this NapiCrdtDoc while `stop()` is in progress.
   */
  stop(): Promise<void>
}

/**
 * File transfer handle exposed to JavaScript.
 *
 * Obtained via `NapiNode.fileTransfer()`. Holds an `Arc<Node>` to create
 * fresh `FileTransfer` handles on each method call (the Rust `FileTransfer`
 * borrows `&Node`, so we can't store it across JS boundaries).
 */
export declare class NapiFileTransfer {
  /**
   * Send a file to a peer.
   *
   * `peer_id` is the recipient's stable `device_id` (RFC 017). The
   * underlying `resolve_peer_id` also accepts device names, prefixes,
   * and legacy Tailscale IDs. Resolves with transfer result on success.
   */
  sendFile(peerId: string, localPath: string, remotePath: string): Promise<NapiTransferResult>
  /**
   * Pull (download) a file from a remote peer.
   *
   * Resolves with transfer result on success.
   */
  pullFile(peerId: string, remotePath: string, localPath: string): Promise<NapiTransferResult>
  /** Auto-accept all incoming file offers, saving files to `output_dir`. */
  autoAccept(outputDir: string): Promise<void>
  /** Auto-reject all incoming file offers. */
  autoReject(): Promise<void>
  /**
   * Subscribe to incoming file offers with a callback.
   *
   * The callback receives a `NapiFileOffer`. Use `autoAccept()` or
   * `autoReject()` for automated handling, or use `onOffer()` for
   * manual inspection of offers.
   * Subscribe to incoming file offers with a callback.
   *
   * The callback receives `(offer, responder)` — call `responder.accept(path)`
   * or `responder.reject(reason)` to handle the offer. If neither is called
   * within 60 seconds, the offer is auto-rejected.
   */
  onOffer(callback: (offer: FileOffer, responder: NapiOfferResponder) => void): void
  /**
   * Subscribe to file transfer events.
   *
   * The callback receives `NapiFileTransferEvent` objects for all
   * transfer lifecycle events (hashing, progress, completed, failed, etc.).
   */
  onEvent(callback: (event: FileTransferEvent) => void): void
  /** Set the maximum allowed transfer size in bytes. */
  setMaxTransferSize(bytes: number): void
}

/**
 * The main truffle node exposed to JavaScript.
 *
 * Lifecycle:
 * 1. `new NapiNode()` — creates an empty wrapper.
 * 2. `await node.start(config)` — builds and starts the underlying `Node<TailscaleProvider>`.
 * 3. Use `getPeers()`, `send()`, `onPeerChange()`, etc.
 * 4. `await node.stop()` — shuts down the node.
 */
export declare class NapiNode {
  /** Create a new (unstarted) NapiNode. */
  constructor()
  /**
   * Install a callback to receive the Tailscale auth URL.
   *
   * Must be called BEFORE `start()`. During startup the Tailscale
   * provider may require interactive authentication; if so, this
   * callback is invoked with the auth URL while `start()` is still
   * waiting. If no callback is installed, `start()` uses the plain
   * build path and may reject with "timed out waiting for
   * authentication" after 5 minutes.
   */
  onAuthRequired(callback: (url: string) => void): void
  /**
   * Start the node with the given configuration.
   *
   * Resolves when the Tailscale sidecar is connected and the node is ready.
   *
   * # Safety
   * This takes `&mut self` in an async context. The caller must ensure that
   * no other calls are made on this NapiNode while `start()` is in progress.
   */
  start(config: NapiNodeConfig): Promise<void>
  /**
   * Stop the node and release all resources.
   *
   * # Safety
   * This takes `&mut self` in an async context. The caller must ensure that
   * no other calls are made on this NapiNode while `stop()` is in progress.
   */
  stop(): Promise<void>
  /** Get the local node's identity. */
  getLocalInfo(): NapiNodeIdentity
  /** Get all known peers. */
  getPeers(): Promise<Array<NapiPeer>>
  /** Resolve a peer identifier (name or ID) to the canonical node ID. */
  resolvePeerId(peerId: string): Promise<string>
  /** Ping a peer and return latency info. */
  ping(peerId: string): Promise<NapiPingResult>
  /** Get health information from the network layer. */
  health(): Promise<NapiHealthInfo>
  /** Send a namespaced message to a specific peer. */
  send(peerId: string, namespace: string, data: Buffer): Promise<void>
  /** Broadcast a namespaced message to all connected peers. */
  broadcast(namespace: string, data: Buffer): Promise<void>
  /**
   * Subscribe to peer change events.
   *
   * The callback receives `NapiPeerEvent` objects whenever peers
   * join, leave, connect, disconnect, or update.
   */
  onPeerChange(callback: (event: PeerEvent) => void): void
  /**
   * Subscribe to messages on a specific namespace.
   *
   * The callback receives `NapiNamespacedMessage` objects.
   */
  onMessage(namespace: string, callback: (msg: NamespacedMessage) => void): void
  /** Get a `NapiFileTransfer` handle for file transfer operations. */
  fileTransfer(): NapiFileTransfer
  /** Get a `NapiProxy` handle for reverse proxy operations. */
  proxy(): NapiProxy
  /**
   * Get a `NapiSyncedStore` handle for synchronized state operations.
   *
   * Each call creates a new store instance with the given `store_id`.
   * Multiple stores can coexist with different IDs.
   */
  syncedStore(storeId: string): NapiSyncedStore
  /**
   * Get a `NapiCrdtDoc` handle for CRDT document operations.
   *
   * Each call creates a new document instance with the given `doc_id`.
   * The document syncs automatically with peers on namespace `"crdt:{doc_id}"`.
   *
   * This is intentionally **synchronous** (matching `synced_store()`).
   * `CrdtDoc::new` is async and calls `tokio::spawn` internally; we enter
   * the napi-rs managed Tokio runtime so the spawn hits a live reactor.
   */
  crdtDoc(docId: string): NapiCrdtDoc
}

/**
 * Responder for accepting or rejecting a file offer from JS.
 *
 * The responder is consumed on the first call to `accept()` or `reject()`.
 * If neither is called, the offer times out after 60 seconds.
 */
export declare class NapiOfferResponder {
  /** Accept the file offer, saving to the specified path. */
  accept(savePath: string): Promise<void>
  /** Reject the file offer with a reason. */
  reject(reason: string): Promise<void>
}

/**
 * Reverse proxy handle exposed to JavaScript.
 *
 * Obtained via `NapiNode.proxy()`. Holds an `Arc<Node>` to create
 * fresh `Proxy` handles on each method call (the Rust `Proxy` borrows
 * `&Node`, so we can't store it across JS boundaries).
 */
export declare class NapiProxy {
  /**
   * Add a reverse proxy that forwards traffic from a TLS port on the mesh
   * to a local target.
   */
  add(config: NapiProxyConfig): Promise<NapiProxyInfo>
  /** Remove a reverse proxy by ID. */
  remove(id: string): Promise<void>
  /** List all active proxies on this node. */
  list(): Promise<Array<NapiProxyInfo>>
  /**
   * Subscribe to proxy lifecycle events.
   *
   * The callback receives `NapiProxyEvent` objects whenever a proxy
   * starts, stops, or encounters an error.
   */
  onEvent(callback: (event: NapiProxyEvent) => void): void
}

/**
 * Synchronized store handle exposed to JavaScript.
 *
 * Obtained via `NapiNode.syncedStore(storeId)`. Each store instance manages
 * device-owned slices of JSON data that are automatically synchronized
 * across the mesh.
 */
export declare class NapiSyncedStore {
  /** Update this device's data in the store. */
  set(data: any): Promise<void>
  /** Get this device's current data, or `null` if `set()` hasn't been called. */
  local(): Promise<any | null>
  /** Get a specific peer's slice by device ID. */
  get(deviceId: string): Promise<NapiSlice | null>
  /** Get all slices (local + remote) as an array. */
  all(): Promise<Array<NapiSlice>>
  /** Get all device IDs that have data in this store. */
  deviceIds(): Promise<Array<string>>
  /** The store identifier. */
  storeId(): string
  /** Current local version number. */
  version(): number
  /**
   * Subscribe to store change events.
   *
   * The callback receives `NapiStoreEvent` objects whenever local data
   * changes, a peer's data is updated, or a peer is removed.
   */
  onChange(callback: (event: StoreEvent) => void): void
  /**
   * Stop the store and cancel all event-forwarding tasks.
   *
   * # Safety
   * This takes `&mut self` in an async context. The caller must ensure that
   * no other calls are made on this NapiSyncedStore while `stop()` is in progress.
   */
  stop(): Promise<void>
}

/** A CRDT document change event delivered to JS. */
export interface NapiCrdtDocEvent {
  /** Event type: "local_change", "remote_change", "peer_synced", "peer_left". */
  eventType: string
  /** Peer identifier (present for remote_change, peer_synced, peer_left events). */
  peerId?: string
}

/** An incoming file offer from a remote peer. */
export interface NapiFileOffer {
  /** Sender's stable `device_id` (ULID) from the RFC 017 hello envelope. */
  fromPeer: string
  /** Human-readable device name of the sending peer. */
  fromName: string
  /** File name being offered. */
  fileName: string
  /** File size in bytes. */
  size: number
  /** Expected SHA-256 hash (hex). */
  sha256: string
  /** Suggested save path from the sender. */
  suggestedPath: string
  /** Unique token for this transfer. */
  token: string
}

/** Events emitted by the file transfer subsystem. */
export interface NapiFileTransferEvent {
  /**
   * Event type: "offer_received", "hashing", "waiting_for_accept",
   * "progress", "completed", "rejected", "failed".
   */
  eventType: string
  /** Transfer token (if applicable). */
  token?: string
  /** File name (if applicable). */
  fileName?: string
  /** Direction: "send" or "receive" (if applicable). */
  direction?: string
  /** Progress info (present for "progress" events). */
  progress?: NapiTransferProgress
  /** Offer info (present for "offer_received" events). */
  offer?: NapiFileOffer
  /** Bytes transferred (present for "completed" events). */
  bytesTransferred?: number
  /** SHA-256 hash (present for "completed" events). */
  sha256?: string
  /** Elapsed seconds (present for "completed" events). */
  elapsedSecs?: number
  /** Reason for rejection or failure. */
  reason?: string
  /** Bytes hashed so far (present for "hashing" events). */
  bytesHashed?: number
  /** Total bytes to hash (present for "hashing" events). */
  totalBytes?: number
}

/** Health information from the network layer. */
export interface NapiHealthInfo {
  /** Current backend state (e.g., "Running", "NeedsLogin"). */
  state: string
  /** Key expiry timestamp (RFC 3339), if applicable. */
  keyExpiry?: string
  /** Active health warnings. */
  warnings: Array<string>
  /** Whether the network is fully operational. */
  healthy: boolean
}

/** A message received on a specific namespace. */
export interface NapiNamespacedMessage {
  /** Sender's stable `device_id` (ULID) from the RFC 017 hello envelope. */
  from: string
  /** Namespace the message was sent on. */
  namespace: string
  /** Application-defined message type. */
  msgType: string
  /** Opaque JSON payload (as a JS value via serde). */
  payload: any
  /** Millisecond Unix timestamp from the sender, if set. */
  timestamp?: number
}

/** Configuration for starting a Node (RFC 017 §7 shape). */
export interface NapiNodeConfig {
  /**
   * Application namespace identifier. Required. Must match
   * `^[a-z][a-z0-9-]{1,31}$`; validated on the Rust side.
   */
  appId: string
  /**
   * Optional human-readable device name. Defaults to the OS hostname.
   * May contain any Unicode characters; the Tailscale hostname is
   * derived automatically.
   */
  deviceName?: string
  /**
   * Optional stable ULID override. Auto-generated (and persisted) when
   * omitted.
   */
  deviceId?: string
  /**
   * Tailscale state directory. Defaults to
   * `{userDataDir}/truffle/{app_id}/{slug(device_name)}`.
   */
  stateDir?: string
  /** Path to the Go sidecar binary. */
  sidecarPath: string
  /** Tailscale auth key for headless authentication. */
  authKey?: string
  /** Whether the node is ephemeral (auto-removed from tailnet on shutdown). */
  ephemeral?: boolean
  /** WebSocket listen port. Defaults to 9417. */
  wsPort?: number
}

/** Identity of the local node (RFC 017 §7.2). */
export interface NapiNodeIdentity {
  /** Application namespace identifier. */
  appId: string
  /** Stable per-device ULID. Primary key for device identity. */
  deviceId: string
  /** Original (unsanitised) device name, as passed by the application. */
  deviceName: string
  /** The Tailscale hostname (`truffle-{app_id}-{slug}`). Debug use only. */
  tailscaleHostname: string
  /** Tailscale stable node ID. Escape hatch for diagnostics. */
  tailscaleId: string
  /** DNS name on the tailnet, if available. */
  dnsName?: string
  /** Tailscale IP address as a string, if available. */
  ip?: string
}

/** A peer as seen by application code (RFC 017 §7.3). */
export interface NapiPeer {
  /** Stable per-device ULID from the remote node. Primary key. */
  deviceId: string
  /** Human-readable device name from the remote node. */
  deviceName: string
  /** Network IP address as a string. */
  ip: string
  /** Whether the peer is online (from Layer 3). */
  online: boolean
  /** Whether there is an active WebSocket connection. */
  wsConnected: boolean
  /** Connection type description (e.g., "direct" or "relay:ord"). */
  connectionType: string
  /** Operating system, if known. */
  os?: string
  /** Last time the peer was seen online (RFC 3339 string). */
  lastSeen?: string
  /** Tailscale stable ID. Escape hatch; most code should use `deviceId`. */
  tailscaleId: string
}

/** A peer change event delivered to JS. */
export interface NapiPeerEvent {
  /** Event type: "joined", "left", "updated", "ws_connected", "ws_disconnected", "auth_required". */
  eventType: string
  /**
   * Stable `device_id` (ULID) of the affected peer. Empty string for
   * `auth_required` events (no associated peer).
   */
  peerId: string
  /** Full peer info (present for joined/updated events). */
  peer?: NapiPeer
  /** Auth URL (present only for auth_required events). */
  authUrl?: string
}

/** Result of a network-level ping. */
export interface NapiPingResult {
  /** Round-trip latency in milliseconds. */
  latencyMs: number
  /** Connection type description (e.g., "direct" or "relay:sfo"). */
  connection: string
  /** Direct peer endpoint address, if available. */
  peerAddr?: string
}

/** Configuration for adding a reverse proxy, received from JavaScript. */
export interface NapiProxyConfig {
  /** Unique identifier (user-chosen or auto-generated). */
  id: string
  /** Human-readable name for the proxy. */
  name: string
  /** Port on which the proxy listens on the tailnet (NAPI uses i32). */
  listenPort: number
  /** Target host (default: "localhost"). */
  targetHost?: string
  /** Target port (the local service port). */
  targetPort: number
  /** Target scheme: "http" or "https" (default: "http"). */
  targetScheme?: string
  /** Whether to announce this proxy on the mesh for discovery (default: true). */
  announce?: boolean
}

/** A proxy lifecycle event delivered to JavaScript. */
export interface NapiProxyEvent {
  /** Event type: "started", "stopped", "error". */
  eventType: string
  /** Proxy ID. */
  id: string
  /** Fully qualified URL (present for "started" events). */
  url?: string
  /** Listen port (present for "started" events). */
  listenPort?: number
  /** Error code (present for "error" events). */
  code?: string
  /** Error message (present for "error" events). */
  message?: string
}

/** Information about a running or configured proxy, returned to JavaScript. */
export interface NapiProxyInfo {
  id: string
  name: string
  listenPort: number
  targetHost: string
  targetPort: number
  targetScheme: string
  url: string
  /** Status: "starting", "running", "stopped", or "error: <message>". */
  status: string
}

/** A versioned slice of data owned by a single device. */
export interface NapiSlice {
  /**
   * Owning device's stable `device_id` (ULID) from the RFC 017 hello
   * envelope.
   */
  deviceId: string
  /** The data (JSON value). */
  data: any
  /** Monotonically increasing version (per-device). */
  version: number
  /** When this version was created (Unix milliseconds). */
  updatedAt: number
}

/** A store change event delivered to JS. */
export interface NapiStoreEvent {
  /** Event type: "local_changed", "peer_updated", "peer_removed". */
  eventType: string
  /**
   * Stable `device_id` (ULID) of the affected device (present for
   * peer_updated / peer_removed events).
   */
  deviceId?: string
  /** Data payload (present for local_changed/peer_updated events). */
  data?: any
  /** Version number (present for peer_updated events). */
  version?: number
}

/** Progress update for an in-flight file transfer. */
export interface NapiTransferProgress {
  /** Unique token for this transfer. */
  token: string
  /** Direction: "send" or "receive". */
  direction: string
  /** File name being transferred. */
  fileName: string
  /** Bytes transferred so far. */
  bytesTransferred: number
  /** Total file size in bytes. */
  totalBytes: number
  /** Current transfer speed in bytes per second. */
  speedBps: number
}

/** Result of a completed file transfer. */
export interface NapiTransferResult {
  /** Number of bytes transferred. */
  bytesTransferred: number
  /** SHA-256 hash of the transferred file. */
  sha256: string
  /** Elapsed time in seconds. */
  elapsedSecs: number
}
