const COMMANDS: &[&str] = &[
    "start",
    "stop",
    "get_local_info",
    "get_peers",
    "ping",
    "health",
    "send_message",
    "broadcast",
    "send_json",
    "send_bytes",
    "broadcast_json",
    "broadcast_bytes",
    "send_file",
    "pull_file",
    "auto_accept",
    "auto_reject",
    "accept_offer",
    "reject_offer",
    // Raw transport (RFC 021 §7, Phase 4) — id-keyed NAPI parity. These
    // generate ACL permission files; raw network access is deny-by-default,
    // so consumers must opt in via their capabilities (not `default.toml`).
    "tcp_open",
    "tcp_read",
    "tcp_write",
    "tcp_end",
    "tcp_close",
    "tcp_listen",
    "tcp_accept",
    "tcp_unlisten",
    "udp_bind",
    "udp_send",
    "udp_recv",
    "udp_close",
    "quic_connect",
    "quic_open_stream",
    "quic_accept_stream",
    "quic_stream_read",
    "quic_stream_write",
    "quic_stream_finish",
    "quic_stream_close",
    "quic_close",
    "quic_listen",
    "quic_accept",
    "quic_listener_close",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
